function getRandomCategory() {
    const categories = ['yoga', 'kickboxing', 'fitness', 'bodybuilding'];
    return categories[Math.floor(Math.random() * categories.length)];
}
export
const DUMMY_EQUIPMENTS = [{
        id: 1,
        name: 'Red T-Shirt',
        description: 'Comfortable and stylish red cotton t-shirt.',
        quantity: 20,
        created_at: '2023-12-01',
        updated_at: '2024-01-15',
        availableQuantity: 15,
        image: 'red_tshirt.jpg',
        category: getRandomCategory(),
        rating: 142,
        totalReviews: 12,
        price: 12,
    },
    {
        id: 2,
        name: 'Blue Hoodie',
        description: 'Warm and cozy blue hoodie for chilly days.',
        quantity: 15,
        created_at: '2023-11-20',
        updated_at: '2024-01-10',
        availableQuantity: 10,
        image: 'blue_hoodie.jpg',
        category: getRandomCategory(),
        rating: 98,
        totalReviews: 8,
        price: 25,
    },
    {
        id: 3,
        name: 'Black Yoga Mat',
        description: 'High-quality non-slip yoga mat in classic black.',
        quantity: 30,
        created_at: '2023-10-05',
        updated_at: '2024-02-01',
        availableQuantity: 25,
        image: 'black_yoga_mat.jpg',
        category: getRandomCategory(),
        rating: 120,
        totalReviews: 10,
        price: 30,
    },
    {
        id: 4,
        name: 'Dumbbell Set',
        description: 'Set of adjustable dumbbells for versatile workouts.',
        quantity: 10,
        created_at: '2023-09-15',
        updated_at: '2024-01-20',
        availableQuantity: 8,
        image: 'dumbbell_set.jpg',
        category: getRandomCategory(),
        rating: 85,
        totalReviews: 6,
        price: 50,
    },
    {
        id: 5,
        name: 'Kickboxing Gloves',
        description: 'Premium leather kickboxing gloves for optimal protection and performance.',
        quantity: 25,
        created_at: '2023-08-22',
        updated_at: '2024-02-05',
        availableQuantity: 20,
        image: 'kickboxing_gloves.jpg',
        category: getRandomCategory(),
        rating: 110,
        totalReviews: 9,
        price: 40,
    },
    {
        id: 6,
        name: 'Resistance Bands',
        description: 'Set of durable resistance bands for strength training and rehabilitation exercises.',
        quantity: 20,
        created_at: '2023-07-10',
        updated_at: '2024-01-25',
        availableQuantity: 18,
        image: 'resistance_bands.jpg',
        category: getRandomCategory(),
        rating: 95,
        totalReviews: 7,
        price: 20,
    },
    {
        id: 7,
        name: 'Yoga Blocks',
        description: 'Lightweight foam yoga blocks to support yoga poses and improve flexibility.',
        quantity: 35,
        created_at: '2023-06-18',
        updated_at: '2024-01-30',
        availableQuantity: 30,
        image: 'yoga_blocks.jpg',
        category: getRandomCategory(),
        rating: 80,
        totalReviews: 5,
        price: 15,
    },
    {
        id: 8,
        name: 'Fitness Tracker',
        description: 'Advanced fitness tracker with heart rate monitor and GPS tracking.',
        quantity: 18,
        created_at: '2023-05-30',
        updated_at: '2024-02-10',
        availableQuantity: 15,
        image: 'fitness_tracker.jpg',
        category: getRandomCategory(),
        rating: 130,
        totalReviews: 11,
        price: 80,
    },
    {
        id: 9,
        name: 'Protein Powder',
        description: 'Premium whey protein powder for muscle recovery and growth.',
        quantity: 40,
        created_at: '2023-04-12',
        updated_at: '2024-02-15',
        availableQuantity: 35,
        image: 'protein_powder.jpg',
        category: getRandomCategory(),
        rating: 150,
        totalReviews: 13,
        price: 35,
    },
    {
        id: 10,
        name: 'Skipping Rope',
        description: 'Adjustable skipping rope for cardio workouts and endurance training.',
        quantity: 22,
        created_at: '2023-03-25',
        updated_at: '2024-02-20',
        availableQuantity: 20,
        image: 'skipping_rope.jpg',
        category: getRandomCategory(),
        rating: 105,
        totalReviews: 8,
        price: 10,
    }
];