export const DUMMY_TRANSACTIONS = [{
        id: 12,
        type: "income",
        title: "Payment Received",
        date: "2024-04-11",
        avatar: "https://example.com/avatar.jpg",
        username: "John Doe",
        amount: "$100",
    },
    {
        id: 10,
        type: "expense",
        title: "Purchase",
        date: "2024-04-10",
        avatar: "https://example.com/avatar.jpg",
        username: "Jane Smith",
        amount: "$50",
    },
    {
        id: 120,
        type: "expense",
        title: "Purchase",
        date: "2024-04-10",
        avatar: "https://example.com/avatar.jpg",
        username: "Jane Smith",
        amount: "$50",
    },
    {
        id: 110,
        type: "expense",
        title: "Purchase",
        date: "2024-04-10",
        avatar: "https://example.com/avatar.jpg",
        username: "Jane Smith",
        amount: "$50",
    },
];