export const DUMMY_NOTIFICATIONS = [{
        id: 1,
        title: "New Message New Message New Message New Message New Message New Message New Message New Message New Message New Message New Message New Message New Message ",
        description: "You have a new message from John Doe.You have a new message from John Doe.You have a new message from John Doe.You have a new message from John Doe.You have a new message from John Doe.",
        date: "2024-04-23T08:00:00Z",
        isMarkedAsRead: false,
    },
    {
        id: 2,
        title: "Payment Received",
        description: "Payment of $100 received for your order.",
        date: "2024-04-22T12:00:00Z",
        isMarkedAsRead: true,
    },
    {
        id: 3,
        title: "Reminder",
        description: "Don't forget to attend the meeting tomorrow.",
        date: "2024-04-21T16:00:00Z",
        isMarkedAsRead: false,
    },
    {
        id: 4,
        title: "New Feature",
        description: "Explore the new features in our latest update.",
        date: "2024-04-20T10:00:00Z",
        isMarkedAsRead: false,
    },
    {
        id: 5,
        title: "Welcome",
        description: "Welcome to our platform. Get started now!",
        date: "2024-04-19T14:00:00Z",
        isMarkedAsRead: true,
    },
    {
        id: 6,
        title: "Product Update",
        description: "Check out the latest updates to our product.",
        date: "2024-04-18T09:00:00Z",
        isMarkedAsRead: false,
    },
    {
        id: 7,
        title: "Event Reminder",
        description: "Join us for our upcoming event next week.",
        date: "2024-04-17T11:00:00Z",
        isMarkedAsRead: false,
    },
    {
        id: 8,
        title: "New Subscriber",
        description: "You have a new subscriber to your channel.",
        date: "2024-04-16T13:00:00Z",
        isMarkedAsRead: true,
    },
    {
        id: 9,
        title: "Upgrade Available",
        description: "Upgrade to our premium plan for more features.",
        date: "2024-04-15T15:00:00Z",
        isMarkedAsRead: false,
    },
    {
        id: 10,
        title: "Feedback Request",
        description: "We'd love to hear your feedback on our service.",
        date: "2024-04-14T17:00:00Z",
        isMarkedAsRead: false,
    },
    {
        id: 11,
        title: "New Blog Post",
        description: "Read our latest blog post on industry trends.",
        date: "2024-04-13T19:00:00Z",
        isMarkedAsRead: true,
    },
    {
        id: 12,
        title: "Account Verification",
        description: "Verify your account to unlock full access.",
        date: "2024-04-12T21:00:00Z",
        isMarkedAsRead: false,
    },
];