export const DUMMY_CLASSES = [{
        id: 1,
        title: "Yoga Class",
        description: "Join us for a relaxing yoga session.",
        coachName: "John Doe",
        coachEmail: "john@example.com",
        date: "21-02-2023",
        time: "12:30 PM - 01:40 PM",
        totalMembers: 40,
    }, {
        id: 2,
        title: "Cardio Workout",
        description: "Get your heart pumping with our intense cardio workout.",
        coachName: "Jane Smith",
        coachEmail: "jane@example.com",
        date: "22-02-2023",
        time: "10:00 AM - 11:00 AM",
        totalMembers: 25,
    }, {
        id: 3,
        title: "Pilates Class",
        description: "Strengthen your core with our Pilates class.",
        coachName: "Alice Johnson",
        coachEmail: "alice@example.com",
        date: "23-02-2023",
        time: "09:00 AM - 10:00 AM",
        totalMembers: 30,
    },
    // Add more classes here...
    {
        id: 10,
        title: "Zumba Dance",
        description: "Join us for an energetic Zumba dance session.",
        coachName: "Michael Brown",
        coachEmail: "michael@example.com",
        date: "30-02-2023",
        time: "06:00 PM - 07:00 PM",
        totalMembers: 20,
    },
];