export const DUMMY_EQUIPMENTS = [{
        id: 1,
        name: 'Red T-Shirt',
        description: 'Comfortable and stylish red cotton t-shirt.',
        quantity: 20,
        max_quantity: 50,
        created_at: '2023-12-01',
        updated_at: '2024-01-15',
        availableQuantity: 15,
        image: 'red_tshirt.jpg',
        category: 'Clothing'
    },
    {
        id: 2,
        name: 'Black Leather Wallet',
        description: 'Genuine leather wallet with multiple card slots.',
        quantity: 30,
        max_quantity: 50,
        created_at: '2023-11-25',
        updated_at: '2024-02-05',
        availableQuantity: 20,
        image: 'black_wallet.jpg',
        category: 'Accessories'
    },
    {
        id: 3,
        name: 'Blue Denim Jeans',
        description: 'Classic blue denim jeans for everyday wear.',
        quantity: 25,
        max_quantity: 40,
        created_at: '2024-01-10',
        updated_at: '2024-03-20',
        availableQuantity: 18,
        image: 'blue_jeans.jpg',
        category: 'Clothing'
    },
    {
        id: 4,
        name: 'Product 4',
        description: 'Description for Product 4',
        quantity: 9,
        max_quantity: 112,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_4.jpg',
        category: 'Category C'
    },
    {
        id: 5,
        name: 'Product 5',
        description: 'Description for Product 5',
        quantity: 10,
        max_quantity: 112,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 12,
        image: 'product_5.jpg',
        category: 'Category C'
    },
    {
        id: 6,
        name: 'Product 6',
        description: 'Description for Product 6',
        quantity: 1,
        max_quantity: 129,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 21,
        image: 'product_6.jpg',
        category: 'Category A'
    },
    {
        id: 7,
        name: 'Product 7',
        description: 'Description for Product 7',
        quantity: 8,
        max_quantity: 71,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_7.jpg',
        category: 'Category A'
    },
    {
        id: 8,
        name: 'Product 8',
        description: 'Description for Product 8',
        quantity: 4,
        max_quantity: 96,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 25,
        image: 'product_8.jpg',
        category: 'Category C'
    },
    {
        id: 9,
        name: 'Product 9',
        description: 'Description for Product 9',
        quantity: 40,
        max_quantity: 98,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 36,
        image: 'product_9.jpg',
        category: 'Category A'
    },
    {
        id: 10,
        name: 'Product 10',
        description: 'Description for Product 10',
        quantity: 30,
        max_quantity: 101,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 20,
        image: 'product_10.jpg',
        category: 'Category A'
    },
    {
        id: 11,
        name: 'Product 11',
        description: 'Description for Product 11',
        quantity: 28,
        max_quantity: 53,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_11.jpg',
        category: 'Category C'
    },
    {
        id: 12,
        name: 'Product 12',
        description: 'Description for Product 12',
        quantity: 9,
        max_quantity: 55,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 12,
        image: 'product_12.jpg',
        category: 'Category A'
    },
    {
        id: 13,
        name: 'Product 13',
        description: 'Description for Product 13',
        quantity: 3,
        max_quantity: 50,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 23,
        image: 'product_13.jpg',
        category: 'Category A'
    },
    {
        id: 14,
        name: 'Product 14',
        description: 'Description for Product 14',
        quantity: 16,
        max_quantity: 92,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 22,
        image: 'product_14.jpg',
        category: 'Category B'
    },
    {
        id: 15,
        name: 'Product 15',
        description: 'Description for Product 15',
        quantity: 39,
        max_quantity: 147,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 13,
        image: 'product_15.jpg',
        category: 'Category A'
    },
    {
        id: 16,
        name: 'Product 16',
        description: 'Description for Product 16',
        quantity: 15,
        max_quantity: 141,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_16.jpg',
        category: 'Category C'
    },
    {
        id: 17,
        name: 'Product 17',
        description: 'Description for Product 17',
        quantity: 20,
        max_quantity: 106,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 33,
        image: 'product_17.jpg',
        category: 'Category C'
    },
    {
        id: 18,
        name: 'Product 18',
        description: 'Description for Product 18',
        quantity: 6,
        max_quantity: 105,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 34,
        image: 'product_18.jpg',
        category: 'Category C'
    },
    {
        id: 19,
        name: 'Product 19',
        description: 'Description for Product 19',
        quantity: 32,
        max_quantity: 132,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 36,
        image: 'product_19.jpg',
        category: 'Category B'
    },
    {
        id: 20,
        name: 'Product 20',
        description: 'Description for Product 20',
        quantity: 48,
        max_quantity: 141,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_20.jpg',
        category: 'Category A'
    },
    {
        id: 21,
        name: 'Product 21',
        description: 'Description for Product 21',
        quantity: 35,
        max_quantity: 98,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 39,
        image: 'product_21.jpg',
        category: 'Category A'
    },
    {
        id: 22,
        name: 'Product 22',
        description: 'Description for Product 22',
        quantity: 26,
        max_quantity: 115,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 19,
        image: 'product_22.jpg',
        category: 'Category A'
    },
    {
        id: 23,
        name: 'Product 23',
        description: 'Description for Product 23',
        quantity: 25,
        max_quantity: 103,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 10,
        image: 'product_23.jpg',
        category: 'Category A'
    },
    {
        id: 24,
        name: 'Product 24',
        description: 'Description for Product 24',
        quantity: 18,
        max_quantity: 93,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 37,
        image: 'product_24.jpg',
        category: 'Category B'
    },
    {
        id: 25,
        name: 'Product 25',
        description: 'Description for Product 25',
        quantity: 5,
        max_quantity: 103,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 37,
        image: 'product_25.jpg',
        category: 'Category A'
    },
    {
        id: 26,
        name: 'Product 26',
        description: 'Description for Product 26',
        quantity: 19,
        max_quantity: 104,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 10,
        image: 'product_26.jpg',
        category: 'Category C'
    },
    {
        id: 27,
        name: 'Product 27',
        description: 'Description for Product 27',
        quantity: 20,
        max_quantity: 52,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_27.jpg',
        category: 'Category A'
    },
    {
        id: 28,
        name: 'Product 28',
        description: 'Description for Product 28',
        quantity: 3,
        max_quantity: 92,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_28.jpg',
        category: 'Category A'
    },
    {
        id: 29,
        name: 'Product 29',
        description: 'Description for Product 29',
        quantity: 16,
        max_quantity: 86,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 30,
        image: 'product_29.jpg',
        category: 'Category A'
    },
    {
        id: 30,
        name: 'Product 30',
        description: 'Description for Product 30',
        quantity: 42,
        max_quantity: 123,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 26,
        image: 'product_30.jpg',
        category: 'Category C'
    },
    {
        id: 31,
        name: 'Product 31',
        description: 'Description for Product 31',
        quantity: 37,
        max_quantity: 144,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 28,
        image: 'product_31.jpg',
        category: 'Category B'
    },
    {
        id: 32,
        name: 'Product 32',
        description: 'Description for Product 32',
        quantity: 25,
        max_quantity: 74,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 12,
        image: 'product_32.jpg',
        category: 'Category A'
    },
    {
        id: 33,
        name: 'Product 33',
        description: 'Description for Product 33',
        quantity: 11,
        max_quantity: 55,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 24,
        image: 'product_33.jpg',
        category: 'Category B'
    },
    {
        id: 34,
        name: 'Product 34',
        description: 'Description for Product 34',
        quantity: 17,
        max_quantity: 84,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 17,
        image: 'product_34.jpg',
        category: 'Category C'
    },
    {
        id: 35,
        name: 'Product 35',
        description: 'Description for Product 35',
        quantity: 25,
        max_quantity: 145,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 10,
        image: 'product_35.jpg',
        category: 'Category B'
    },
    {
        id: 36,
        name: 'Product 36',
        description: 'Description for Product 36',
        quantity: 22,
        max_quantity: 54,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 21,
        image: 'product_36.jpg',
        category: 'Category C'
    },
    {
        id: 37,
        name: 'Product 37',
        description: 'Description for Product 37',
        quantity: 36,
        max_quantity: 149,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 24,
        image: 'product_37.jpg',
        category: 'Category B'
    },
    {
        id: 38,
        name: 'Product 38',
        description: 'Description for Product 38',
        quantity: 41,
        max_quantity: 51,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 19,
        image: 'product_38.jpg',
        category: 'Category C'
    },
    {
        id: 39,
        name: 'Product 39',
        description: 'Description for Product 39',
        quantity: 16,
        max_quantity: 53,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_39.jpg',
        category: 'Category C'
    },
    {
        id: 40,
        name: 'Product 40',
        description: 'Description for Product 40',
        quantity: 32,
        max_quantity: 56,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 28,
        image: 'product_40.jpg',
        category: 'Category C'
    },
    {
        id: 41,
        name: 'Product 41',
        description: 'Description for Product 41',
        quantity: 49,
        max_quantity: 77,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 33,
        image: 'product_41.jpg',
        category: 'Category A'
    },
    {
        id: 42,
        name: 'Product 42',
        description: 'Description for Product 42',
        quantity: 29,
        max_quantity: 85,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 16,
        image: 'product_42.jpg',
        category: 'Category C'
    },
    {
        id: 43,
        name: 'Product 43',
        description: 'Description for Product 43',
        quantity: 15,
        max_quantity: 127,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 30,
        image: 'product_43.jpg',
        category: 'Category A'
    },
    {
        id: 44,
        name: 'Product 44',
        description: 'Description for Product 44',
        quantity: 19,
        max_quantity: 82,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 20,
        image: 'product_44.jpg',
        category: 'Category B'
    },
    {
        id: 45,
        name: 'Product 45',
        description: 'Description for Product 45',
        quantity: 50,
        max_quantity: 121,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_45.jpg',
        category: 'Category B'
    },
    {
        id: 46,
        name: 'Product 46',
        description: 'Description for Product 46',
        quantity: 36,
        max_quantity: 111,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 17,
        image: 'product_46.jpg',
        category: 'Category A'
    },
    {
        id: 47,
        name: 'Product 47',
        description: 'Description for Product 47',
        quantity: 12,
        max_quantity: 58,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 11,
        image: 'product_47.jpg',
        category: 'Category C'
    },
    {
        id: 48,
        name: 'Product 48',
        description: 'Description for Product 48',
        quantity: 39,
        max_quantity: 103,
        created_at: '2024-04-01',
        updated_at: "2024,02,01",
        availableQuantity: 25,
        image: 'product_48.jpg',
        category: 'Category C'
    },
    {
        id: 49,
        name: 'Product 49',
        description: 'Description for Product 49',
        quantity: 47,
        max_quantity: 139,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 28,
        image: 'product_49.jpg',
        category: 'Category A'
    },
    {
        id: 1,
        name: 'Red T-Shirt',
        description: 'Comfortable and stylish red cotton t-shirt.',
        quantity: 20,
        max_quantity: 50,
        created_at: '2023-12-01',
        updated_at: '2024-01-15',
        availableQuantity: 15,
        image: 'red_tshirt.jpg',
        category: 'Clothing'
    },
    {
        id: 2,
        name: 'Black Leather Wallet',
        description: 'Genuine leather wallet with multiple card slots.',
        quantity: 30,
        max_quantity: 50,
        created_at: '2023-11-25',
        updated_at: '2024-02-05',
        availableQuantity: 20,
        image: 'black_wallet.jpg',
        category: 'Accessories'
    },
    {
        id: 3,
        name: 'Blue Denim Jeans',
        description: 'Classic blue denim jeans for everyday wear.',
        quantity: 25,
        max_quantity: 40,
        created_at: '2024-01-10',
        updated_at: '2024-03-20',
        availableQuantity: 18,
        image: 'blue_jeans.jpg',
        category: 'Clothing'
    },
    {
        id: 4,
        name: 'Product 4',
        description: 'Description for Product 4',
        quantity: 9,
        max_quantity: 112,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_4.jpg',
        category: 'Category C'
    },
    {
        id: 5,
        name: 'Product 5',
        description: 'Description for Product 5',
        quantity: 10,
        max_quantity: 112,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 12,
        image: 'product_5.jpg',
        category: 'Category C'
    },
    {
        id: 6,
        name: 'Product 6',
        description: 'Description for Product 6',
        quantity: 1,
        max_quantity: 129,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 21,
        image: 'product_6.jpg',
        category: 'Category A'
    },
    {
        id: 7,
        name: 'Product 7',
        description: 'Description for Product 7',
        quantity: 8,
        max_quantity: 71,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_7.jpg',
        category: 'Category A'
    },
    {
        id: 8,
        name: 'Product 8',
        description: 'Description for Product 8',
        quantity: 4,
        max_quantity: 96,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 25,
        image: 'product_8.jpg',
        category: 'Category C'
    },
    {
        id: 9,
        name: 'Product 9',
        description: 'Description for Product 9',
        quantity: 40,
        max_quantity: 98,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 36,
        image: 'product_9.jpg',
        category: 'Category A'
    },
    {
        id: 10,
        name: 'Product 10',
        description: 'Description for Product 10',
        quantity: 30,
        max_quantity: 101,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 20,
        image: 'product_10.jpg',
        category: 'Category A'
    },
    {
        id: 11,
        name: 'Product 11',
        description: 'Description for Product 11',
        quantity: 28,
        max_quantity: 53,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_11.jpg',
        category: 'Category C'
    },
    {
        id: 12,
        name: 'Product 12',
        description: 'Description for Product 12',
        quantity: 9,
        max_quantity: 55,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 12,
        image: 'product_12.jpg',
        category: 'Category A'
    },
    {
        id: 13,
        name: 'Product 13',
        description: 'Description for Product 13',
        quantity: 3,
        max_quantity: 50,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 23,
        image: 'product_13.jpg',
        category: 'Category A'
    },
    {
        id: 14,
        name: 'Product 14',
        description: 'Description for Product 14',
        quantity: 16,
        max_quantity: 92,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 22,
        image: 'product_14.jpg',
        category: 'Category B'
    },
    {
        id: 15,
        name: 'Product 15',
        description: 'Description for Product 15',
        quantity: 39,
        max_quantity: 147,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 13,
        image: 'product_15.jpg',
        category: 'Category A'
    },
    {
        id: 16,
        name: 'Product 16',
        description: 'Description for Product 16',
        quantity: 15,
        max_quantity: 141,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_16.jpg',
        category: 'Category C'
    },
    {
        id: 17,
        name: 'Product 17',
        description: 'Description for Product 17',
        quantity: 20,
        max_quantity: 106,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 33,
        image: 'product_17.jpg',
        category: 'Category C'
    },
    {
        id: 18,
        name: 'Product 18',
        description: 'Description for Product 18',
        quantity: 6,
        max_quantity: 105,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 34,
        image: 'product_18.jpg',
        category: 'Category C'
    },
    {
        id: 19,
        name: 'Product 19',
        description: 'Description for Product 19',
        quantity: 32,
        max_quantity: 132,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 36,
        image: 'product_19.jpg',
        category: 'Category B'
    },
    {
        id: 20,
        name: 'Product 20',
        description: 'Description for Product 20',
        quantity: 48,
        max_quantity: 141,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_20.jpg',
        category: 'Category A'
    },
    {
        id: 21,
        name: 'Product 21',
        description: 'Description for Product 21',
        quantity: 35,
        max_quantity: 98,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 39,
        image: 'product_21.jpg',
        category: 'Category A'
    },
    {
        id: 22,
        name: 'Product 22',
        description: 'Description for Product 22',
        quantity: 26,
        max_quantity: 115,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 19,
        image: 'product_22.jpg',
        category: 'Category A'
    },
    {
        id: 23,
        name: 'Product 23',
        description: 'Description for Product 23',
        quantity: 25,
        max_quantity: 103,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 10,
        image: 'product_23.jpg',
        category: 'Category A'
    },
    {
        id: 24,
        name: 'Product 24',
        description: 'Description for Product 24',
        quantity: 18,
        max_quantity: 93,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 37,
        image: 'product_24.jpg',
        category: 'Category B'
    },
    {
        id: 25,
        name: 'Product 25',
        description: 'Description for Product 25',
        quantity: 5,
        max_quantity: 103,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 37,
        image: 'product_25.jpg',
        category: 'Category A'
    },
    {
        id: 26,
        name: 'Product 26',
        description: 'Description for Product 26',
        quantity: 19,
        max_quantity: 104,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 10,
        image: 'product_26.jpg',
        category: 'Category C'
    },
    {
        id: 27,
        name: 'Product 27',
        description: 'Description for Product 27',
        quantity: 20,
        max_quantity: 52,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_27.jpg',
        category: 'Category A'
    },
    {
        id: 28,
        name: 'Product 28',
        description: 'Description for Product 28',
        quantity: 3,
        max_quantity: 92,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_28.jpg',
        category: 'Category A'
    },
    {
        id: 29,
        name: 'Product 29',
        description: 'Description for Product 29',
        quantity: 16,
        max_quantity: 86,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 30,
        image: 'product_29.jpg',
        category: 'Category A'
    },
    {
        id: 30,
        name: 'Product 30',
        description: 'Description for Product 30',
        quantity: 42,
        max_quantity: 123,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 26,
        image: 'product_30.jpg',
        category: 'Category C'
    },
    {
        id: 31,
        name: 'Product 31',
        description: 'Description for Product 31',
        quantity: 37,
        max_quantity: 144,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 28,
        image: 'product_31.jpg',
        category: 'Category B'
    },
    {
        id: 32,
        name: 'Product 32',
        description: 'Description for Product 32',
        quantity: 25,
        max_quantity: 74,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 12,
        image: 'product_32.jpg',
        category: 'Category A'
    },
    {
        id: 33,
        name: 'Product 33',
        description: 'Description for Product 33',
        quantity: 11,
        max_quantity: 55,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 24,
        image: 'product_33.jpg',
        category: 'Category B'
    },
    {
        id: 34,
        name: 'Product 34',
        description: 'Description for Product 34',
        quantity: 17,
        max_quantity: 84,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 17,
        image: 'product_34.jpg',
        category: 'Category C'
    },
    {
        id: 35,
        name: 'Product 35',
        description: 'Description for Product 35',
        quantity: 25,
        max_quantity: 145,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 10,
        image: 'product_35.jpg',
        category: 'Category B'
    },
    {
        id: 36,
        name: 'Product 36',
        description: 'Description for Product 36',
        quantity: 22,
        max_quantity: 54,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 21,
        image: 'product_36.jpg',
        category: 'Category C'
    },
    {
        id: 37,
        name: 'Product 37',
        description: 'Description for Product 37',
        quantity: 36,
        max_quantity: 149,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 24,
        image: 'product_37.jpg',
        category: 'Category B'
    },
    {
        id: 38,
        name: 'Product 38',
        description: 'Description for Product 38',
        quantity: 41,
        max_quantity: 51,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 19,
        image: 'product_38.jpg',
        category: 'Category C'
    },
    {
        id: 39,
        name: 'Product 39',
        description: 'Description for Product 39',
        quantity: 16,
        max_quantity: 53,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_39.jpg',
        category: 'Category C'
    },
    {
        id: 40,
        name: 'Product 40',
        description: 'Description for Product 40',
        quantity: 32,
        max_quantity: 56,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 28,
        image: 'product_40.jpg',
        category: 'Category C'
    },
    {
        id: 41,
        name: 'Product 41',
        description: 'Description for Product 41',
        quantity: 49,
        max_quantity: 77,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 33,
        image: 'product_41.jpg',
        category: 'Category A'
    },
    {
        id: 42,
        name: 'Product 42',
        description: 'Description for Product 42',
        quantity: 29,
        max_quantity: 85,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 16,
        image: 'product_42.jpg',
        category: 'Category C'
    },
    {
        id: 43,
        name: 'Product 43',
        description: 'Description for Product 43',
        quantity: 15,
        max_quantity: 127,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 30,
        image: 'product_43.jpg',
        category: 'Category A'
    },
    {
        id: 44,
        name: 'Product 44',
        description: 'Description for Product 44',
        quantity: 19,
        max_quantity: 82,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 20,
        image: 'product_44.jpg',
        category: 'Category B'
    },
    {
        id: 45,
        name: 'Product 45',
        description: 'Description for Product 45',
        quantity: 50,
        max_quantity: 121,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_45.jpg',
        category: 'Category B'
    },
    {
        id: 46,
        name: 'Product 46',
        description: 'Description for Product 46',
        quantity: 36,
        max_quantity: 111,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 17,
        image: 'product_46.jpg',
        category: 'Category A'
    },
    {
        id: 47,
        name: 'Product 47',
        description: 'Description for Product 47',
        quantity: 12,
        max_quantity: 58,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 11,
        image: 'product_47.jpg',
        category: 'Category C'
    },
    {
        id: 48,
        name: 'Product 48',
        description: 'Description for Product 48',
        quantity: 39,
        max_quantity: 103,
        created_at: '2024-04-01',
        updated_at: "2024,02,01",
        availableQuantity: 25,
        image: 'product_48.jpg',
        category: 'Category C'
    },
    {
        id: 49,
        name: 'Product 49',
        description: 'Description for Product 49',
        quantity: 47,
        max_quantity: 139,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 28,
        image: 'product_49.jpg',
        category: 'Category A'
    }, {
        id: 1,
        name: 'Red T-Shirt',
        description: 'Comfortable and stylish red cotton t-shirt.',
        quantity: 20,
        max_quantity: 50,
        created_at: '2023-12-01',
        updated_at: '2024-01-15',
        availableQuantity: 15,
        image: 'red_tshirt.jpg',
        category: 'Clothing'
    },
    {
        id: 2,
        name: 'Black Leather Wallet',
        description: 'Genuine leather wallet with multiple card slots.',
        quantity: 30,
        max_quantity: 50,
        created_at: '2023-11-25',
        updated_at: '2024-02-05',
        availableQuantity: 20,
        image: 'black_wallet.jpg',
        category: 'Accessories'
    },
    {
        id: 3,
        name: 'Blue Denim Jeans',
        description: 'Classic blue denim jeans for everyday wear.',
        quantity: 25,
        max_quantity: 40,
        created_at: '2024-01-10',
        updated_at: '2024-03-20',
        availableQuantity: 18,
        image: 'blue_jeans.jpg',
        category: 'Clothing'
    },
    {
        id: 4,
        name: 'Product 4',
        description: 'Description for Product 4',
        quantity: 9,
        max_quantity: 112,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_4.jpg',
        category: 'Category C'
    },
    {
        id: 5,
        name: 'Product 5',
        description: 'Description for Product 5',
        quantity: 10,
        max_quantity: 112,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 12,
        image: 'product_5.jpg',
        category: 'Category C'
    },
    {
        id: 6,
        name: 'Product 6',
        description: 'Description for Product 6',
        quantity: 1,
        max_quantity: 129,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 21,
        image: 'product_6.jpg',
        category: 'Category A'
    },
    {
        id: 7,
        name: 'Product 7',
        description: 'Description for Product 7',
        quantity: 8,
        max_quantity: 71,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_7.jpg',
        category: 'Category A'
    },
    {
        id: 8,
        name: 'Product 8',
        description: 'Description for Product 8',
        quantity: 4,
        max_quantity: 96,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 25,
        image: 'product_8.jpg',
        category: 'Category C'
    },
    {
        id: 9,
        name: 'Product 9',
        description: 'Description for Product 9',
        quantity: 40,
        max_quantity: 98,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 36,
        image: 'product_9.jpg',
        category: 'Category A'
    },
    {
        id: 10,
        name: 'Product 10',
        description: 'Description for Product 10',
        quantity: 30,
        max_quantity: 101,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 20,
        image: 'product_10.jpg',
        category: 'Category A'
    },
    {
        id: 11,
        name: 'Product 11',
        description: 'Description for Product 11',
        quantity: 28,
        max_quantity: 53,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_11.jpg',
        category: 'Category C'
    },
    {
        id: 12,
        name: 'Product 12',
        description: 'Description for Product 12',
        quantity: 9,
        max_quantity: 55,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 12,
        image: 'product_12.jpg',
        category: 'Category A'
    },
    {
        id: 13,
        name: 'Product 13',
        description: 'Description for Product 13',
        quantity: 3,
        max_quantity: 50,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 23,
        image: 'product_13.jpg',
        category: 'Category A'
    },
    {
        id: 14,
        name: 'Product 14',
        description: 'Description for Product 14',
        quantity: 16,
        max_quantity: 92,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 22,
        image: 'product_14.jpg',
        category: 'Category B'
    },
    {
        id: 15,
        name: 'Product 15',
        description: 'Description for Product 15',
        quantity: 39,
        max_quantity: 147,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 13,
        image: 'product_15.jpg',
        category: 'Category A'
    },
    {
        id: 16,
        name: 'Product 16',
        description: 'Description for Product 16',
        quantity: 15,
        max_quantity: 141,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 31,
        image: 'product_16.jpg',
        category: 'Category C'
    },
    {
        id: 17,
        name: 'Product 17',
        description: 'Description for Product 17',
        quantity: 20,
        max_quantity: 106,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 33,
        image: 'product_17.jpg',
        category: 'Category C'
    },
    {
        id: 18,
        name: 'Product 18',
        description: 'Description for Product 18',
        quantity: 6,
        max_quantity: 105,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 34,
        image: 'product_18.jpg',
        category: 'Category C'
    },
    {
        id: 19,
        name: 'Product 19',
        description: 'Description for Product 19',
        quantity: 32,
        max_quantity: 132,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 36,
        image: 'product_19.jpg',
        category: 'Category B'
    },
    {
        id: 20,
        name: 'Product 20',
        description: 'Description for Product 20',
        quantity: 48,
        max_quantity: 141,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_20.jpg',
        category: 'Category A'
    },
    {
        id: 21,
        name: 'Product 21',
        description: 'Description for Product 21',
        quantity: 35,
        max_quantity: 98,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 39,
        image: 'product_21.jpg',
        category: 'Category A'
    },
    {
        id: 22,
        name: 'Product 22',
        description: 'Description for Product 22',
        quantity: 26,
        max_quantity: 115,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 19,
        image: 'product_22.jpg',
        category: 'Category A'
    },
    {
        id: 23,
        name: 'Product 23',
        description: 'Description for Product 23',
        quantity: 25,
        max_quantity: 103,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 10,
        image: 'product_23.jpg',
        category: 'Category A'
    },
    {
        id: 24,
        name: 'Product 24',
        description: 'Description for Product 24',
        quantity: 18,
        max_quantity: 93,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 37,
        image: 'product_24.jpg',
        category: 'Category B'
    },
    {
        id: 25,
        name: 'Product 25',
        description: 'Description for Product 25',
        quantity: 5,
        max_quantity: 103,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 37,
        image: 'product_25.jpg',
        category: 'Category A'
    },
    {
        id: 26,
        name: 'Product 26',
        description: 'Description for Product 26',
        quantity: 19,
        max_quantity: 104,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 10,
        image: 'product_26.jpg',
        category: 'Category C'
    },
    {
        id: 27,
        name: 'Product 27',
        description: 'Description for Product 27',
        quantity: 20,
        max_quantity: 52,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_27.jpg',
        category: 'Category A'
    },
    {
        id: 28,
        name: 'Product 28',
        description: 'Description for Product 28',
        quantity: 3,
        max_quantity: 92,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_28.jpg',
        category: 'Category A'
    },
    {
        id: 29,
        name: 'Product 29',
        description: 'Description for Product 29',
        quantity: 16,
        max_quantity: 86,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 30,
        image: 'product_29.jpg',
        category: 'Category A'
    },
    {
        id: 30,
        name: 'Product 30',
        description: 'Description for Product 30',
        quantity: 42,
        max_quantity: 123,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 26,
        image: 'product_30.jpg',
        category: 'Category C'
    },
    {
        id: 31,
        name: 'Product 31',
        description: 'Description for Product 31',
        quantity: 37,
        max_quantity: 144,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 28,
        image: 'product_31.jpg',
        category: 'Category B'
    },
    {
        id: 32,
        name: 'Product 32',
        description: 'Description for Product 32',
        quantity: 25,
        max_quantity: 74,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 12,
        image: 'product_32.jpg',
        category: 'Category A'
    },
    {
        id: 33,
        name: 'Product 33',
        description: 'Description for Product 33',
        quantity: 11,
        max_quantity: 55,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 24,
        image: 'product_33.jpg',
        category: 'Category B'
    },
    {
        id: 34,
        name: 'Product 34',
        description: 'Description for Product 34',
        quantity: 17,
        max_quantity: 84,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 17,
        image: 'product_34.jpg',
        category: 'Category C'
    },
    {
        id: 35,
        name: 'Product 35',
        description: 'Description for Product 35',
        quantity: 25,
        max_quantity: 145,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 10,
        image: 'product_35.jpg',
        category: 'Category B'
    },
    {
        id: 36,
        name: 'Product 36',
        description: 'Description for Product 36',
        quantity: 22,
        max_quantity: 54,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 21,
        image: 'product_36.jpg',
        category: 'Category C'
    },
    {
        id: 37,
        name: 'Product 37',
        description: 'Description for Product 37',
        quantity: 36,
        max_quantity: 149,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 24,
        image: 'product_37.jpg',
        category: 'Category B'
    },
    {
        id: 38,
        name: 'Product 38',
        description: 'Description for Product 38',
        quantity: 41,
        max_quantity: 51,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 19,
        image: 'product_38.jpg',
        category: 'Category C'
    },
    {
        id: 39,
        name: 'Product 39',
        description: 'Description for Product 39',
        quantity: 16,
        max_quantity: 53,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_39.jpg',
        category: 'Category C'
    },
    {
        id: 40,
        name: 'Product 40',
        description: 'Description for Product 40',
        quantity: 32,
        max_quantity: 56,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 28,
        image: 'product_40.jpg',
        category: 'Category C'
    },
    {
        id: 41,
        name: 'Product 41',
        description: 'Description for Product 41',
        quantity: 49,
        max_quantity: 77,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 33,
        image: 'product_41.jpg',
        category: 'Category A'
    },
    {
        id: 42,
        name: 'Product 42',
        description: 'Description for Product 42',
        quantity: 29,
        max_quantity: 85,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 16,
        image: 'product_42.jpg',
        category: 'Category C'
    },
    {
        id: 43,
        name: 'Product 43',
        description: 'Description for Product 43',
        quantity: 15,
        max_quantity: 127,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 30,
        image: 'product_43.jpg',
        category: 'Category A'
    },
    {
        id: 44,
        name: 'Product 44',
        description: 'Description for Product 44',
        quantity: 19,
        max_quantity: 82,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 20,
        image: 'product_44.jpg',
        category: 'Category B'
    },
    {
        id: 45,
        name: 'Product 45',
        description: 'Description for Product 45',
        quantity: 50,
        max_quantity: 121,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 35,
        image: 'product_45.jpg',
        category: 'Category B'
    },
    {
        id: 46,
        name: 'Product 46',
        description: 'Description for Product 46',
        quantity: 36,
        max_quantity: 111,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 17,
        image: 'product_46.jpg',
        category: 'Category A'
    },
    {
        id: 47,
        name: 'Product 47',
        description: 'Description for Product 47',
        quantity: 12,
        max_quantity: 58,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 11,
        image: 'product_47.jpg',
        category: 'Category C'
    },
    {
        id: 48,
        name: 'Product 48',
        description: 'Description for Product 48',
        quantity: 39,
        max_quantity: 103,
        created_at: '2024-04-01',
        updated_at: "2024,02,01",
        availableQuantity: 25,
        image: 'product_48.jpg',
        category: 'Category C'
    },
    {
        id: 49,
        name: 'Product 49',
        description: 'Description for Product 49',
        quantity: 47,
        max_quantity: 139,
        created_at: '2024-04-01',
        updated_at: '2024-04-05',
        availableQuantity: 28,
        image: 'product_49.jpg',
        category: 'Category A'
    }
]